### PR TITLE
player: Use the livepeer.js player

### PR DESCRIPTION
**Pull request by victorges**
This is to use the livepeer.js player instead of reimplementing all of the logic on this project.

The player will handle calling the playback info API already and also all the complexities of configuring
an HLS player on non-Apple devices.

I'm also deprecating some internal configs from the player just to simplify things. Specifically, the only
ways to specify source video are now the `v` or `url` query strings. The specific `live/recording/vod`
ones have been removed.

This implements #10

### CODE REVIEW

**Comment by victorges** [comment]
Preview on: https://bafybeifohsd7c2s6agamnlwslgh4kzf4dqixmzunwv7mlojisdpduboylm.on.fleek.co/

**Review by 0xcadams — APPROVED** [review]
LGTM!

**Comment by 0xcadams** [comment]
One thing - you probably want to override the body html to remove the margin

```css
body {
    margin: 0px;
}
```

**Comment by adamsoffer** [comment]
Looks great! Just have the same comment as Chase - let's make sure we set the body margin to 0.

**Pull request merged**
